### ISSUE TITLE
urgent problem with the latest whmcs (8.10) - conflict with .it class

### ISSUE THREAD

**Issue by barianiluca** [rendermani/ascio-whmcs-plugin#23]
Dear,

today we have updated to the latest whmcs (8.10) and here we see a conflict with your ascio-whmcs plugin, like this (this is the output of the cron script run in debug mode):

```
Domain Status Synchronisation
PHP Fatal error:  Cannot declare class it, because the name is already in use in /var/www/clients/client4/web130/web/modules/registrars/ascio/tlds/it/it.php on line 2

Fatal error: Cannot declare class it, because the name is already in use in /var/www/clients/client4/web130/web/modules/registrars/ascio/tlds/it/it.php on line 2
[WHMCS Application] ERROR: Whoops\Exception\ErrorException: Cannot declare class it, because the name is already in use in /var/www/clients/client4/web130/web/modules/registrars/ascio/tlds/it/it.php:2 Stack trace: #0 /var/www/clients/client4/web130/web/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError() #1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown() #2 {main} {"exception":"[object] (Whoops\\Exception\\ErrorException(code: 64): Cannot declare class it, because the name is already in use at /var/www/clients/client4/web130/web/modules/registrars/ascio/tlds/it/it.php:2)"} []
Whoops\Exception\ErrorException: Cannot declare class it, because the name is already in use in /var/www/clients/client4/web130/web/modules/registrars/ascio/tlds/it/it.php:2

#0 /var/www/clients/client4/web130/web/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError()
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}
```

in my opinion this is because you don't use namespace on your code, so that a `it` class conflict with an already present on ~~whmcs itself~~ another part of the plugin.
Please can you give it a check asap?

thank you

**Comment by barianiluca** [comment]
For now I have put this workaround:

```
-- tlds/it/it.php

<?php
namespace ascio\tlds

```

and

```
-- lib/Request.php

<?php
[...]
use ascio\tlds;
```

but i'm not sure that this is enough.

**Comment by barianiluca** [comment]
this issue rise from urgent, to very urgent, due that the above fix is not enough. all the plugin should be under namespace, otherswise will no work with the latest whmcs 8.10 and php 8.1

**Comment by barianiluca** [comment]
after digging more into that problem i saw that probably the bug was on the tlds/tn.it/tn.it.php
Here the class is named:

```
-- tlds/tn.it/tn.it.php

<?php
class it extends Request {
[...]
```

changed with:

```
-- tlds/tn.it/tn.it.php

<?php
class tn_it extends Request {
[...]
```

**Comment by rendermani** [comment]
this is fixed in the newest version. Added namespaces
